env:
  browser: true
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  "react/jsx-filename-extension":
    - 1
    - extensions:
      - ".js"
      - ".jsx"
globals:
    it: true
    should: true
    jest: true
